### PR TITLE
Scala 3 preparation

### PR DESCRIPTION
**Pull request by ajrnz**
This PR build on 2 previous PRs for scala 3 support

cssparse and pythonparse now compile and pass tests

fastparse still has some test failures

scalaparse has an issue with a macro

### CODE REVIEW

**Comment by davidrwood** [comment]
Is this essentially competing with https://github.com/com-lihaoyi/fastparse/pull/267 ?

**Comment by kyri-petrou** [comment]
Hi there 👋 I'm one of the contributors of [Caliban](https://github.com/ghostdogpr/caliban), and I've been occasionally checking the status of the Scala 3 release of fastparse. Caliban offers supports Scala 2.12, 2.13 and 3. The Scala 2.x versions use fastparse to parse the GraphQL queries and cats-parse for Scala 3 until fastparse becomes available for Scala 3 as well.

I wanted to mention that once you're at a stage with this PR that you're confident in (or have a snapshot release), I'd be happy to test the Scala 3 version of fastparse in Caliban. Since we already have the Scala 2 code, unit tests and benchmarks (for the graphql query parsing), it should be relatively low effort to implement and test

**Comment by davidrwood** [comment]
@ajrnz Just wondering if you've got a chance to get this wrapped up? It seems like it's very close...

**Comment by lihaoyi** [comment]
superseded by https://github.com/com-lihaoyi/fastparse/pull/271

**Pull request closed without merging**
