### PR TITLE
Changelog for 3.0.0

### PR DESCRIPTION
**Pull request by lihaoyi**

### CODE REVIEW

**Comment by lihaoyi** [comment]
Gonna try to get https://github.com/com-lihaoyi/fastparse/pull/244 merged as well before we release 3.x

**Comment by lefou** [comment]
[Milestone 3.0.0](https://github.com/com-lihaoyi/fastparse/issues?q=is%3Aclosed+milestone%3A3.0.0)

**Review by lefou — APPROVED** [review]
Looks good to me.

**Review by reid-spencer — APPROVED** [review]
LGTM

**Pull request merged**
