### PR TITLE
Preparation work for Scala 3

### PR DESCRIPTION
**Pull request by lolgab**
This commit does some preparation work to allow the port to Scala 3
The idea is to move all the code using macros to the `src-2` directory,
update the dependencies to the ones supporting Scala 3 ( mill, geny,
sourcecode, utest ), avoid depending on `scala-reflect` if it's Scala 3
and fixing the compile errors the Scala 3 compiler gives before reaching
the absent macros.

### CODE REVIEW

**Comment by ngbinh** [comment]
awesome!

**Comment by SethTisue** [comment]
is this superseded by #262?

**Comment by lolgab** [comment]
@SethTisue I guess it is! Thank you for commenting.
Closing as superseded by #262

**Comment by lolgab** [comment]
Reopening since the PR targets this branch, so we need to understand if we want to split this into two PRs or not.

**Comment by lolgab** [comment]
Changed #262 to target master so I can close this safely as superseded

**Pull request closed without merging**
